services:
  - type: web
    name: codeup-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerCommand: null
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: suaChaveSecretaAqui
      - key: DATABASE_URL
        value: jdbc:postgresql://sua-url
      - key: DATABASE_USER
        value: user
      - key: DATABASE_PASSWORD
        value: pass
